### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by dakshhmehta** [selahattinunlu/laravel-api-query-builder#1]
As I see in the code,

Virtually, everything is possible to do in where condition, eager loading and some cool stuff. But, to use this package in one of our upcoming project. We would like to know what about security. What we have taken care for security?

Thanks.

**Comment by selahattinunlu** [comment]
@dakshhmehta I understand your concerns. I did not see any security vulnerability yet. But in the future I will try to solve problem if a security problem. 

I continue to actively develop the package. I would be glad if you help me with your team. (issue or pull request)

I wonder if there is another problem?
