### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::toBase()

### ISSUE THREAD

**Issue by algarves** [selahattinunlu/laravel-api-query-builder#13]
After the last update I'm having problems with version 5.1 of Laravel.

https://github.com/selahattinunlu/laravel-api-query-builder/blob/master/src/QueryBuilder.php#L406

**Comment by selahattinunlu** [comment]
@khrisnet  Sorry, I will check the issue.

**Comment by selahattinunlu** [comment]
@khrisnet  I released new version to fix this issue. Sorry again :) Can you please update the package and test again? If you inform me, I will be happy. Thanks :)

**Comment by algarves** [comment]
Perfect @selahattinunlu, thank you for the agility and the feedback.

**Comment by selahattinunlu** [comment]
You are welcome @khrisnet :)
