### ISSUE TITLE
Null values

### ISSUE THREAD

**Issue by robsontenorio** [selahattinunlu/laravel-api-query-builder#16]
I cant find examples about null values

https://github.com/selahattinunlu/laravel-api-query-builder/wiki/Other-Examples

Is that possible?
`/users?updated_at=null`

**Comment by selahattinunlu** [comment]
@robsontenorio  There is no way for now. I will handle it.

**Comment by robsontenorio** [comment]
@selahattinunlu Thanks! By the way `not null` statment woud be usefull as well ;)

**Comment by selahattinunlu** [comment]
@robsontenorio Great! Thanks! By the way, I may not finish today. But I hope I can finish it tomorrow :)

**Comment by selahattinunlu** [comment]
@robsontenorio 

We need a token to determine it.
"null" may cause a problem when a column has got "null" value as string.

Do you have any suggestion about it?

**Comment by robsontenorio** [comment]
It is really a good question. I think you should release an version with a token chosen by you, and wait for people and bugs around it.

I like "null", because its hard some one use "null" as string  value for database field.

**Comment by robsontenorio** [comment]
`updated_at=[null]`  ?

**Comment by selahattinunlu** [comment]
@robsontenorio  I think it can be better instead of "null". 👍 

?updated_at=[null] (whereNull)
?updated_at!=[null] (whereNotNull)

**Comment by selahattinunlu** [comment]
@robsontenorio  I released new version. Can you please inform me after trying?

**Comment by robsontenorio** [comment]
@selahattinunlu worked like a charm :)  By the way, will you consider #15 ? My implementation has 4 lines changed.

**Comment by selahattinunlu** [comment]
Great! :) I will handle to the other problem at the first opportunity. @robsontenorio
