### ISSUE TITLE
Change default limit, orderBy and excludedParameters parameters in Lumen

### ISSUE THREAD

**Issue by mdafzal** [selahattinunlu/laravel-api-query-builder#17]
Can you please throw some light on how to change default limit, orderBy and excludedParameters parameters in Lumen ?

**Comment by robsontenorio** [comment]
@mdafzal  Have you tried this?

https://github.com/selahattinunlu/laravel-api-query-builder/wiki/9.-How-do-exclude-parameters-from-queries%3F

**Comment by selahattinunlu** [comment]
@robsontenorio is right! 
@mdafzal Did it fix? can you please inform me?

**Comment by mdafzal** [comment]
Thanks @robsontenorio @selahattinunlu 

Fixed it! I am using Lumen 5.2.9 and  had to make following changes
#1) Create config directory in the root of project and add file api-query-builder.php with configuration options
#2) Add this line $app->configure( 'api-query-builder' ) to bootstrap/app.php

**Comment by selahattinunlu** [comment]
Great! @mdafzal :)
