### ISSUE TITLE
Support for orWhere

### ISSUE THREAD

**Issue by alekslyse** [selahattinunlu/laravel-api-query-builder#18]
Are you planning to add support for an orWhere parameter with the same operators as the where statement. Its not uncommon to need a where or where query so it should be a nice addition in my opinion.

**Comment by juniorb2ss** [comment]
Something like 
`?name=Jhon&orName=Micael` 

or maybe
`?name=(Jhon|Micael)`

result: `where (name = 'Jhon' OR name = 'Micael')`

**Comment by alekslyse** [comment]
Yes, actually both would be good.

**Comment by selahattinunlu** [comment]
@alekslyse @juniorb2ss 

Hi guys. Firstly, thanks for suggestion!
You can use "whereIn" to make this.

`/api/users?age[]=18&age[]=23`
The resulting query = Users::whereIn('age', [18, 23])

It gives same result exactly.

https://github.com/selahattinunlu/laravel-api-query-builder/wiki/Other-Examples#where-queries

**Comment by selahattinunlu** [comment]
I think issue is resolved. But if you don't think like me please open again.
