### ISSUE TITLE
URL Token Param

### ISSUE THREAD

**Issue by algarves** [selahattinunlu/laravel-api-query-builder#2]
Hi,

I'm having trouble passing the token as a parameter of the request. By default it's playing as a column.

Any suggestions about it to get around this?

**Comment by selahattinunlu** [comment]
Hi @khrisnet,

Thank you for your issue. I released new version and fixed this issue.

3e141c7815111dd09b3299858b28ca090d0b0fb4 You can check this commit

Added "excludedParameters" to config/api-query-builder.php file.

if you want to except any parameter as global, you should add this parameter into "api-query-builder.php" - "exludedParameters"

if you want to except any parameter for just specific query builder (eg: UserQueryBuilder)
then you should add this parameter into "UserQueryBuilder.php" - "excludedParameters"

I am glad, if i can help you :)

**Comment by algarves** [comment]
Hello @selahattinunlu 

Thanks for attention
Congratulations on the project and your feedback :+1:

**Comment by selahattinunlu** [comment]
Thanks again @khrisnet :+1:  :)
