### ISSUE TITLE
Laravel 5 autoload serviceproviders

### ISSUE THREAD

**Issue by markwalet** [selahattinunlu/laravel-api-query-builder#30]
Just like the title says.

**Comment by robsontenorio** [comment]
https://laravel.com/docs/5.5/packages#package-discovery

**Comment by markwalet** [comment]
Can someone implement this?

**Comment by robsontenorio** [comment]
Waiting @selahattinunlu  approval ...

PR https://github.com/selahattinunlu/laravel-api-query-builder/pull/34

**Comment by markwalet** [comment]
This repo seems abandoned

**Comment by romano1996** [comment]
I tried a while ago to become the maintainer of this repo, he told me I could by didn't give me any permissions..

**Comment by selahattinunlu** [comment]
@romano1996 Sorry! I sent the invite if you want to maintain the project still.
