### ISSUE TITLE
Lumen compatibility 

### ISSUE THREAD

**Issue by OskarD** [selahattinunlu/laravel-api-query-builder#4]
Support for Lumen would be great! Right now, I get an uncaught ReflectionException:

> ( ! ) Fatal error: Uncaught ReflectionException: Class path.storage does not exist in /home/vagrant/Code/parties-api/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 738

**Comment by OskarD** [comment]
Turns out the problem is on the other side of the equation (Lumen), sorry

**Comment by OskarD** [comment]
It would still be cool to have Lumen support, though. After some research, it seems like all the problems can be addressed within this repo to allow for Lumen support

**Comment by selahattinunlu** [comment]
@OskarD I will add Lumen support today, thanks for advice :)

**Comment by selahattinunlu** [comment]
@OskarD I released new version for lumen compatibility. 

Please remember, add these lines in bootstrap/app.php:
$app->withFacades();
$app->withEloquent();
$app->register(Unlu\Laravel\Api\LumenServiceProvider::class);
