### ISSUE TITLE
Lumen configuration file

### ISSUE THREAD

**Issue by OskarD** [selahattinunlu/laravel-api-query-builder#5]
Thank you so much for Lumen compatibility!

Is there any way to allow for extending/modifying the functionality with Lumen? If not, some way to do that would be very useful.

**Comment by selahattinunlu** [comment]
You can change configuration at runtime.

Eg: app/bootstrap.php file

```
config()->set('api-query-builder.limit', 1);
config()->set('api-query-builder.orderBy', [
       [
            'column' => 'id',
            'direction' => 'desc'
        ]
]);
```

And you can access all configuration like this:
`config('api-query-builder')`

I am glad if I can help you :)
