### ISSUE TITLE
What is the best way to override 'orderBy' configuration?

### ISSUE THREAD

**Issue by macias67** [selahattinunlu/laravel-api-query-builder#8]
I have a table with a primary key like this "model_id", I do not using "id", so what is the best way to override the array configuration (`config/api-query-builder.php`)?

**Comment by GustavoHekel** [comment]
I fixed this by commenting $this->orderBy = config('api-query-builder.orderBy'); on the QueryBuilder constructor class

**Comment by selahattinunlu** [comment]
Hi @Macias67 and @GustavoHekel  Firstly, I'm sorry, I'm late.

There is multiple way for this.

## 1. You can change configuration file.

```
return [

    'limit' => 15,
    'orderBy' => [
        [
            'column' => 'id',
            'direction' => 'desc'
        ]
    ],
    'excludedParameters' => [],
];
```

to

```
return [

    'limit' => 15,
    'orderBy' => [],
    'excludedParameters' => [],
];
```

So, there is no default configuration anymore.

## 2. Create new QueryBuilder class that it extends base QueryBuilder like this:

```
class YourQueryBuilder extends QueryBuilder
    {
        public function __construct(Model $model, Request $request)
       {
           parent::__construct($model, $request);
           $this->orderBy = [];
       }
    }
```

I hope I could help you.
